repos:
  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        entry: npx prettier --write
        language: system
        files: \.(js|ts|json|md)$
      - id: eslint
        name: ESLint
        entry: npx eslint --fix
        language: system
        files: \.(js|ts)$
